# Prometheus Configuration
# FinancIA 2030

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'financia-2030'
    env: 'dev'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Rule files
rule_files:
  # - "alerts.yml"

# Scrape configurations
scrape_configs:
  # Backend API metrics
  - job_name: 'fastapi'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  # PostgreSQL metrics (requires postgres_exporter)
  # - job_name: 'postgresql'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']
      
  # Redis metrics (requires redis_exporter)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']
